In [2]:
import numpy as np

In [4]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
# We can now use array notations to access value at any index, e.g.
arr[8]    # Will output value stored at index 8 in numpy array

8

In [6]:
# We can use slicing on numpy array, similar to python list
# E.g. 
print(arr[0:5])
print(arr[5:])

[0 1 2 3 4]
[ 5  6  7  8  9 10]


In [10]:
# numpy array differs from python list in terms of broadcast ability
# Broadcasting means, updating a range of indexes/slice of array with one value
# means broadcast a value to numpy array or part of array
# E.g. 

print('original array is {}'.format(arr))
arr[3:] = 30   # will update all the valus to after index 3
print('array after broadcast is {}'.format(arr))

original array is [0 1 2 3 3 3 3 3 3 3 3]
array after broadcast is [ 0  1  2 30 30 30 30 30 30 30 30]


In [11]:
""" 
Note: numpy array do not return copy of the original array after slicing, rather it just gives you a view to original array 
"""
arr = np.arange(0,11)
# E.g.
arr_sub_arr = arr[1:4]

print('original array is {}'.format(arr))
print('original arr_sub_arr is {}'.format(arr_sub_arr))

original array is [ 0  1  2  3  4  5  6  7  8  9 10]
original arr_sub_arr is [1 2 3]


In [12]:
# Now if we broadcast some value to subarray, it will reflect to original array as well
arr_sub_arr[:] = 99
print('Now arr_sub_arr is {}'.format(arr_sub_arr))
print('Now array is {}'.format(arr))

Now arr_sub_arr is [99 99 99]
Now array is [ 0 99 99 99  4  5  6  7  8  9 10]


In [14]:
# if we want a seperate copy of the array, we need to request it specifically by using copy() method of numpy array
# like
arr_copy = arr.copy()
arr_copy

array([ 0, 99, 99, 99,  4,  5,  6,  7,  8,  9, 10])

# Indexing and Slicing 2-D array

In [16]:
arr_2d = np.array([[5,10,15], [20,25,30], [35,40,45]])
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [17]:
# We may now use c/c++ style i.e. using 2 array notations to grab value at particular row and column
# E.g. for picking 10, i.e. at row 0 and column 1,
arr_2d[0][1]

10

In [18]:
# however, the prefered way of doing it with numpy is to use single bracket with row and column index seperated by comma
# E.g. 
arr_2d[0,1]

10

In [21]:
# We may use this slicing concept to grab a submatrix from the given matrix
# E.g. 
print(arr_2d[:2,1:])

print (arr_2d[1:,1:])

[[10 15]
 [25 30]]
[[25 30]
 [40 45]]


In [25]:
# Conditional Selection
# Create sample array
arr = np.arange(11)
print('original array is:\n {}'.format(arr))

# Now we may apply some condition on whole array and store the result in different array
bool_arr = arr > 5
print("Boolean array based on condition applied to array is:\n {}".format(bool_arr))

# Now if we can use this bool_arr to extract values(indexes we are having True in bool_arr) from sample array, 
print("Selected array is:\n {}".format(arr[bool_arr]))

original array is:
 [ 0  1  2  3  4  5  6  7  8  9 10]
Boolean array based on condition applied to array is:
 [False False False False False False  True  True  True  True  True]
Selected array is:
 [ 6  7  8  9 10]


In [26]:
# We may directly use conditions inside the array notation
# E.g. 
arr[arr>3]

array([ 4,  5,  6,  7,  8,  9, 10])

In [28]:
# Some practice example for 2d array slicing
arr = np.arange(0,50).reshape(5,10)
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [29]:
arr[1:3,3:5]

array([[13, 14],
       [23, 24]])