In [1]:
import numpy as np

In [3]:
# array on array
# We may directly use some airthemtic operation between 2 numpy arrays with just the array name
# E.g. 
arr= np.arange(11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
# Adding 2 array element wise, 
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [5]:
# We may do other arithmetic operations in similar way
# Add
sumarr = arr + arr
print('sum = {}'.format(sumarr))

# substract
diffarr = sumarr - arr
print('diff = {}'.format(diffarr))

sum = [ 0  2  4  6  8 10 12 14 16 18 20]
diff = [ 0  1  2  3  4  5  6  7  8  9 10]


In [6]:
# Array to scalar operations, means operation of elements of array with a single number
# E.g. 
diffarr + 1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

# Numpy division special case
-- Numpy doesn't throw an if we try divide by 0, like normal python. numpy just issues a runtime warning, if we try to divide a number by zero. 

-- Result may vary depending on number invlolved in divion with zero

-- E.g. 


In [12]:
arr = np.arange(10)
# If we divide 0 by 0, we get 'nan' with a runtime warning
print(arr/0)
# If we divide any other number by zero, we get 'inf' as result
print(0/arr)

[nan inf inf inf inf inf inf inf inf inf]
[nan  0.  0.  0.  0.  0.  0.  0.  0.  0.]


C:\Users\Admin\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: RuntimeWarning: divide by zero encountered in true_divide
  This is separate from the ipykernel package so we can avoid doing imports until
C:\Users\Admin\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: RuntimeWarning: invalid value encountered in true_divide
  This is separate from the ipykernel package so we can avoid doing imports until
C:\Users\Admin\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: RuntimeWarning: invalid value encountered in true_divide
  """


In [13]:
# Universal array Functions

# we may calculate square root of each element in array
print(np.sqrt(arr))


array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [14]:
# exponential
print(np.exp(arr))

[1.00000000e+00 2.71828183e+00 7.38905610e+00 2.00855369e+01
 5.45981500e+01 1.48413159e+02 4.03428793e+02 1.09663316e+03
 2.98095799e+03 8.10308393e+03]
