# Array with Array

In [2]:
import numpy as np

# We may perform airthmetic operations between 2 arrays provided both arrays are of same size
# E.g.

arr1 = np.arange(0,10)
arr2 = np.arange(11,15)

arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
arr2

array([11, 12, 13, 14])

In [4]:
arr1 + arr2

ValueError: operands could not be broadcast together with shapes (10,) (4,) 

In [7]:
arr2 = np.arange(11,21) 

In [8]:
arr1 + arr2

array([11, 13, 15, 17, 19, 21, 23, 25, 27, 29])

# Array scalar operations

In [ ]:
# We may perorm arithmetic operations on whole array 