* indexing and slicing with numpy array works pretty much same as string/list indexing and slicing in python

In [3]:
import numpy as np

arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
# to get element at index 3,
arr[3]

4

In [5]:
# to get elements between index 1 to  index 6
arr[1:6]

array([2, 3, 4, 5, 6])

In [6]:
# to get elements up to index 5
arr[:5]

array([1, 2, 3, 4, 5])

In [7]:
# to to get everything after a particular index
arr[4:]

array([ 5,  6,  7,  8,  9, 10])

* numpy arrays differ from a normal python list with the ability to broadcast a value to a range of indexes

In [18]:
# E.g.
tmparr = np.arange(1,11)
print("demo original array:  {}".format(tmparr))

# Broadcast a value of 25 to all elements between index 1 to 5
tmparr[1:5] = 25
print("demo array after broadcast:  {}".format(tmparr))

"""
Note: slicing will not create deep copy of original array in normal scenario
Means, if we change the sliced array, the changes will reflect to original array.
"""
# E.g.
tmparr = np.arange(1,11)
print("original array:  {}".format(tmparr))

slicedarr = tmparr[2:8]
print("sliced array:  {}".format(slicedarr))

# Now if we use update values in sliced array, it will reflect to original array
# broadcast 50 to all elements of sliced array
slicedarr[:] = 50
print("sliced array:  {}".format(slicedarr))

print("original array:  {}".format(tmparr))

# even if we change single element in sliced array, it will reflect to original array
slicedarr[4] = 999
print("original array:  {}".format(tmparr))

# to get a copy from sliced array not just a reference, use copy() method
# Lets reform the array
origarr = np.arange(1,11)
print("original array:  {}".format(origarr))

copyarr = origarr.copy()

slicedarr = copyarr[1:5]
slicedarr[:] = 999
print("sliced array:  {}".format(slicedarr))

print("original array is still the same:  {}".format(origarr))

print("copied arr is changed:  {}".format(copyarr))




demo original array:  [ 1  2  3  4  5  6  7  8  9 10]
demo array after broadcast:  [ 1 25 25 25 25  6  7  8  9 10]
original array:  [ 1  2  3  4  5  6  7  8  9 10]
sliced array:  [3 4 5 6 7 8]
sliced array:  [50 50 50 50 50 50]
original array:  [ 1  2 50 50 50 50 50 50  9 10]
original array:  [  1   2  50  50  50  50 999  50   9  10]
original array:  [ 1  2  3  4  5  6  7  8  9 10]
sliced array:  [999 999 999 999]
original array is still the same:  [ 1  2  3  4  5  6  7  8  9 10]
copied arr is changed:  [  1 999 999 999 999   6   7   8   9  10]


# 2-D Array indexing and Slicing
* We may index a 2-D array in 2 ways using numpy
    * Using the c-like 2 array notation i.e. arr[r][c], where r is index of row and c is index of column 
    * passing row and column indexes as comma seperated value in a single array notation. like arr[r,c]
    
 Refer to below examples
    

In [19]:
import numpy as np

# first let us create an 2-D array in numpy
# delcare a 2-D list in python
tmplist = [[5,10,15], [20,25,30], [35,40,45]]
array_2d = np.array(tmplist)

array_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [20]:
# Use 2 consecutive array notation to access elements at any index
# to grab '25', row index is 1 and column index is also 1
array_2d[1][1]  

25

In [22]:
# same can be achieved by passing row and column index as comma seperated value in single array notation to array_2d
array_2d[1,1]

25

In [27]:
# slicing 2d array, getting top right corner element 
# i.e. 10,15
 #       25,30
array_2d[:2, 1:]  # take till 2nd row and 1st column onwards

array([[10, 15],
       [25, 30]])

In [29]:
# let us take a bigger array 
np_array = np.arange(30)
np_array


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [30]:
# now reshape it to a 2-D array of 5*6 matrix
np_array = np_array.reshape(5,6)
np_array

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [31]:
# now let us grab 
# 7,8,9
# 13,14,15
# 19,20,21
# For this, will take values from row 1 to 3 and column 1 to 3
np_array[1:4, 1:4] # will have pass index+1, so for grabbing till row index 3, we passed 4

array([[ 7,  8,  9],
       [13, 14, 15],
       [19, 20, 21]])

In [32]:
# play around, will grab
# 15,16,17
# 21,22,23
# 27,28,29
# for this, need values from row 2 till end, column from 3 till end
np_array[2:, 3:]

array([[15, 16, 17],
       [21, 22, 23],
       [27, 28, 29]])

# applying some condition/operation on whole array
* With Numpy we may apply some specific condition on whole array

Please refer below examples for the same

In [33]:
# If we apply any condition on whole array, will get boolean array in result
# E.g.
np_array = np.arange(1,50)
np_array 

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [36]:
# Now let us apply some condition on this array
bool_array = np_array < 15
bool_array

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False])

In [37]:
# we may see in above example that we got an array of bools, now if we use this result array of bools to original array
# we will get all the elements with True at thier index positions
np_array[bool_array]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [38]:
# Now instead of using a intermediate array like bool_array, 
# we may use the condition directly in array notation in place of indexes. e.g.
# To get all the element less than 15 from np_array
np_array[np_array < 15]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [43]:
# We may use other operation on whole array, like
# Below operation will add 1 to whole array
np_array = np_array + 1
np_array

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,
       21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37,
       38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52])